"""Generate registry-derived reference pages for the docs site.

Renders Markdown from `registry.py` (metrics, operators),
`configurator.category_offers` (the check x data-type applicability
matrix), and `cli.build_parser()` (commands, flags, exit codes) --
never from hand-maintained prose -- so these reference pages cannot drift
from the code they describe.

Run as `python -m dbfresh.docsgen` (wired into `just docs`, which generates
then runs `mkdocs build --strict`). The output directory is a build
artifact: it is gitignored and never committed.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from dbfresh import registry
from dbfresh.adapters.base import Category
from dbfresh.cli import build_parser
from dbfresh.configurator import category_offers
from dbfresh.engine import Status, exit_code

DEFAULT_OUTPUT_DIR = Path("docs/reference")

_GENERATED_BANNER = (
    "<!--\n"
    "Generated by `python -m dbfresh.docsgen` from the code -- do not edit\n"
    "by hand. Regenerate with `just docs`.\n"
    "-->\n"
)

_EXIT_CODE_MEANING = {
    Status.OK: "all clear",
    Status.SKIPPED: "all clear",
    Status.WARN: "soft-bound violations only",
    Status.FAIL: "value violations",
    Status.ERROR: "unreachable / query error",
}


def render_metrics() -> str:
    """The metric reference table, one row per registered metric."""
    lines = [_GENERATED_BANNER, "# Metric reference", ""]
    lines.append("| metric | tier | required | description |")
    lines.append("| --- | --- | --- | --- |")
    for spec in registry.METRICS:
        required = f"`{spec.required}`" if spec.required else "—"
        row = f"`{spec.name}` | {spec.tier} | {required} | {spec.description}"
        lines.append(f"| {row} |")
    lines.append("")
    return "\n".join(lines)


def render_operators() -> str:
    """The expectation-operator reference table."""
    lines = [_GENERATED_BANNER, "# Expectation operator reference", ""]
    lines.append("| operator | meaning |")
    lines.append("| --- | --- |")
    for spec in registry.OPERATORS:
        lines.append(f"| `{spec.operator}` | {spec.meaning} |")
    lines.append("")
    return "\n".join(lines)


def _matrix_columns() -> list[str]:
    """Column-level check names in first-seen order across categories."""
    columns: list[str] = []
    for category in Category:
        for check_name in category_offers(category):
            if check_name not in columns:
                columns.append(check_name)
    return columns


def render_matrix() -> str:
    """The check x data-type applicability matrix, from category_offers."""
    columns = _matrix_columns()
    lines = [_GENERATED_BANNER, "# Check x data-type applicability matrix", ""]
    lines.append(
        "Column-level checks offered per canonical column category. "
        "Table-level checks -- `row_count`, `schema`, and "
        "assertions -- apply regardless of column category and are not "
        "shown here."
    )
    lines.append("")
    header = ["category", *columns]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("| " + " | ".join(["---"] * len(header)) + " |")
    for category in Category:
        offered = set(category_offers(category))
        row = [f"`{category.value}`"]
        row += ["✓" if name in offered else "" for name in columns]
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")
    return "\n".join(lines)


def _subparsers_action(parser: argparse.ArgumentParser) -> argparse._SubParsersAction:
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    raise RuntimeError("parser declares no subcommands")


def _command_help(sub_action: argparse._SubParsersAction) -> dict[str, str]:
    """One-line help text per subcommand name, as shown in top-level --help."""
    return {pseudo.dest: pseudo.help or "" for pseudo in sub_action._choices_actions}


def _flag_rows(subparser: argparse.ArgumentParser) -> list[str]:
    rows = []
    for action in subparser._actions:
        if isinstance(action, argparse._HelpAction):
            continue
        flags = (
            ", ".join(action.option_strings)
            if action.option_strings
            else (f"`{action.dest}`")
        )
        default = (
            ""
            if action.default in (None, False, argparse.SUPPRESS)
            else (str(action.default))
        )
        rows.append(f"| {flags} | {default} | {action.help or ''} |")
    return rows


def render_cli() -> str:
    """The CLI reference: every command, its flags, and exit codes."""
    parser = build_parser()
    sub_action = _subparsers_action(parser)
    command_help = _command_help(sub_action)

    lines = [_GENERATED_BANNER, "# CLI reference", ""]
    lines.append(f"`{parser.prog}` supports a global `--version` flag and the")
    lines.append("following subcommands.")
    lines.append("")

    for name, subparser in sub_action.choices.items():
        lines.append(f"## `{parser.prog} {name}`")
        lines.append("")
        lines.append(command_help.get(name, ""))
        lines.append("")
        lines.append("| flag | default | help |")
        lines.append("| --- | --- | --- |")
        lines.extend(_flag_rows(subparser))
        lines.append("")

    lines.append("## Exit codes")
    lines.append("")
    lines.append("Worst status across all checks.")
    lines.append("")
    lines.append("| code | status | meaning |")
    lines.append("| --- | --- | --- |")
    seen_codes: set[int] = set()
    for status in Status:
        code = exit_code(status)
        if code in seen_codes:
            continue
        seen_codes.add(code)
        statuses_at_code = [s.value for s in Status if exit_code(s) == code]
        meaning = _EXIT_CODE_MEANING[status]
        lines.append(f"| {code} | {' / '.join(statuses_at_code)} | {meaning} |")
    lines.append("")
    return "\n".join(lines)


def write_all(output_dir: Path = DEFAULT_OUTPUT_DIR) -> dict[str, str]:
    """Render every generated reference page and write it under ``output_dir``.

    Returns the rendered ``{filename: content}`` mapping so callers (tests,
    the lockstep check) can inspect content without re-reading from disk.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    pages = {
        "metrics.md": render_metrics(),
        "operators.md": render_operators(),
        "matrix.md": render_matrix(),
        "cli.md": render_cli(),
    }
    for name, content in pages.items():
        (output_dir / name).write_text(content)
    return pages


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Generate registry-derived reference docs for the mkdocs site."
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help=f"where to write the generated pages (default: {DEFAULT_OUTPUT_DIR})",
    )
    args = parser.parse_args(argv)
    pages = write_all(args.output_dir)
    print(f"wrote {len(pages)} generated reference page(s) to {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
